-- -------------------------------------------------------------
-- 
-- File Name: hdl_prj\hdlsrc\hydrophone\CORDIC_Iteration_block1.vhd
-- Created: 2017-07-03 12:54:44
-- 
-- Generated by MATLAB 9.2 and HDL Coder 3.10
-- 
-- -------------------------------------------------------------


-- -------------------------------------------------------------
-- 
-- Module: CORDIC_Iteration_block1
-- Source Path: hydrophone/Subsystem/Complex to Magnitude-Angle HDL Optimized2/CORDIC_Iteration
-- Hierarchy Level: 2
-- 
-- -------------------------------------------------------------
LIBRARY IEEE;
USE IEEE.std_logic_1164.ALL;
USE IEEE.numeric_std.ALL;

ENTITY CORDIC_Iteration_block1 IS
  PORT( xin                               :   IN    std_logic_vector(26 DOWNTO 0);  -- sfix27_E14
        yin                               :   IN    std_logic_vector(26 DOWNTO 0);  -- sfix27_E14
        idx                               :   IN    std_logic_vector(5 DOWNTO 0);  -- ufix6
        xout                              :   OUT   std_logic_vector(26 DOWNTO 0);  -- sfix27_E14
        yout                              :   OUT   std_logic_vector(26 DOWNTO 0)  -- sfix27_E14
        );
END CORDIC_Iteration_block1;


ARCHITECTURE rtl OF CORDIC_Iteration_block1 IS

  -- Signals
  SIGNAL xin_signed                       : signed(26 DOWNTO 0);  -- sfix27_E14
  SIGNAL yin_signed                       : signed(26 DOWNTO 0);  -- sfix27_E14
  SIGNAL idx_unsigned                     : unsigned(5 DOWNTO 0);  -- ufix6
  SIGNAL CORDIC_Iteration_x1              : signed(26 DOWNTO 0);  -- sfix27_E14
  SIGNAL CORDIC_Iteration_y1              : signed(26 DOWNTO 0);  -- sfix27_E14
  SIGNAL CORDIC_Iteration_cast            : unsigned(7 DOWNTO 0);  -- uint8
  SIGNAL CORDIC_Iteration_cast_1          : unsigned(7 DOWNTO 0);  -- uint8
  SIGNAL xout_tmp                         : signed(26 DOWNTO 0);  -- sfix27_E14
  SIGNAL yout_tmp                         : signed(26 DOWNTO 0);  -- sfix27_E14

BEGIN
  xin_signed <= signed(xin);

  yin_signed <= signed(yin);

  idx_unsigned <= unsigned(idx);

  -- Magnitude Optimized CORDIC Vectoring Mode Iteration Unit
  CORDIC_Iteration_cast <= resize(idx_unsigned, 8);
  CORDIC_Iteration_y1 <= SHIFT_RIGHT(yin_signed, to_integer(CORDIC_Iteration_cast));
  CORDIC_Iteration_cast_1 <= resize(idx_unsigned, 8);
  CORDIC_Iteration_x1 <= SHIFT_RIGHT(xin_signed, to_integer(CORDIC_Iteration_cast_1));
  
  xout_tmp <= xin_signed - CORDIC_Iteration_y1 WHEN yin_signed < to_signed(16#0000000#, 27) ELSE
      xin_signed + CORDIC_Iteration_y1;
  
  yout_tmp <= yin_signed + CORDIC_Iteration_x1 WHEN yin_signed < to_signed(16#0000000#, 27) ELSE
      yin_signed - CORDIC_Iteration_x1;

  xout <= std_logic_vector(xout_tmp);

  yout <= std_logic_vector(yout_tmp);

END rtl;

