-- -------------------------------------------------------------
-- 
-- File Name: hdl_prj\hdlsrc\hydrophone\Quadrant_Mapper_block.vhd
-- Created: 2017-07-03 12:54:44
-- 
-- Generated by MATLAB 9.2 and HDL Coder 3.10
-- 
-- -------------------------------------------------------------


-- -------------------------------------------------------------
-- 
-- Module: Quadrant_Mapper_block
-- Source Path: hydrophone/Subsystem/Complex to Magnitude-Angle HDL Optimized1/Quadrant_Mapper
-- Hierarchy Level: 2
-- 
-- -------------------------------------------------------------
LIBRARY IEEE;
USE IEEE.std_logic_1164.ALL;
USE IEEE.numeric_std.ALL;

ENTITY Quadrant_Mapper_block IS
  PORT( xin                               :   IN    std_logic_vector(26 DOWNTO 0);  -- sfix27_E14
        yin                               :   IN    std_logic_vector(26 DOWNTO 0);  -- sfix27_E14
        xout                              :   OUT   std_logic_vector(26 DOWNTO 0);  -- sfix27_E14
        yout                              :   OUT   std_logic_vector(26 DOWNTO 0)  -- sfix27_E14
        );
END Quadrant_Mapper_block;


ARCHITECTURE rtl OF Quadrant_Mapper_block IS

  -- Signals
  SIGNAL xin_signed                       : signed(26 DOWNTO 0);  -- sfix27_E14
  SIGNAL abs_y                            : signed(27 DOWNTO 0);  -- sfix28_E14
  SIGNAL abs_cast                         : signed(27 DOWNTO 0);  -- sfix28_E14
  SIGNAL xAbs                             : signed(26 DOWNTO 0);  -- sfix27_E14
  SIGNAL yin_signed                       : signed(26 DOWNTO 0);  -- sfix27_E14
  SIGNAL abs_y_1                          : signed(27 DOWNTO 0);  -- sfix28_E14
  SIGNAL abs_cast_1                       : signed(27 DOWNTO 0);  -- sfix28_E14
  SIGNAL yAbs                             : signed(26 DOWNTO 0);  -- sfix27_E14
  SIGNAL relop_relop1                     : std_logic;
  SIGNAL xout_tmp                         : signed(26 DOWNTO 0);  -- sfix27_E14
  SIGNAL yout_tmp                         : signed(26 DOWNTO 0);  -- sfix27_E14

BEGIN
  xin_signed <= signed(xin);

  abs_cast <= resize(xin_signed, 28);
  
  abs_y <=  - (abs_cast) WHEN xin_signed < to_signed(16#0000000#, 27) ELSE
      resize(xin_signed, 28);
  xAbs <= abs_y(26 DOWNTO 0);

  yin_signed <= signed(yin);

  abs_cast_1 <= resize(yin_signed, 28);
  
  abs_y_1 <=  - (abs_cast_1) WHEN yin_signed < to_signed(16#0000000#, 27) ELSE
      resize(yin_signed, 28);
  yAbs <= abs_y_1(26 DOWNTO 0);

  
  relop_relop1 <= '1' WHEN xAbs > yAbs ELSE
      '0';

  
  xout_tmp <= yAbs WHEN relop_relop1 = '0' ELSE
      xAbs;

  xout <= std_logic_vector(xout_tmp);

  
  yout_tmp <= xAbs WHEN relop_relop1 = '0' ELSE
      yAbs;

  yout <= std_logic_vector(yout_tmp);

END rtl;

