-- -------------------------------------------------------------
-- 
-- File Name: hdl_prj\hdlsrc\hydrophone\RADIX2FFT_bitNatural_block1.vhd
-- Created: 2017-07-03 12:54:48
-- 
-- Generated by MATLAB 9.2 and HDL Coder 3.10
-- 
-- -------------------------------------------------------------


-- -------------------------------------------------------------
-- 
-- Module: RADIX2FFT_bitNatural_block1
-- Source Path: hydrophone/Subsystem/FFT HDL Optimized2/RADIX2FFT_bitNatural
-- Hierarchy Level: 2
-- 
-- -------------------------------------------------------------
LIBRARY IEEE;
USE IEEE.std_logic_1164.ALL;
USE IEEE.numeric_std.ALL;

ENTITY RADIX2FFT_bitNatural_block1 IS
  PORT( clk                               :   IN    std_logic;
        reset                             :   IN    std_logic;
        enb                               :   IN    std_logic;
        dout_10_1_re                      :   IN    std_logic_vector(25 DOWNTO 0);  -- sfix26_En14
        dout_10_1_im                      :   IN    std_logic_vector(25 DOWNTO 0);  -- sfix26_En14
        dout_10_1_vld                     :   IN    std_logic;
        softReset                         :   IN    std_logic;
        dout_re1                          :   OUT   std_logic_vector(25 DOWNTO 0);  -- sfix26_En14
        dout_im1                          :   OUT   std_logic_vector(25 DOWNTO 0);  -- sfix26_En14
        dout_vld1                         :   OUT   std_logic
        );
END RADIX2FFT_bitNatural_block1;


ARCHITECTURE rtl OF RADIX2FFT_bitNatural_block1 IS

  -- Component Declarations
  COMPONENT SimpleDualPortRAM_generic
    GENERIC( AddrWidth                    : integer;
             DataWidth                    : integer
             );
    PORT( clk                             :   IN    std_logic;
          enb                             :   IN    std_logic;
          wr_din                          :   IN    std_logic_vector(DataWidth - 1 DOWNTO 0);  -- generic width
          wr_addr                         :   IN    std_logic_vector(AddrWidth - 1 DOWNTO 0);  -- generic width
          wr_en                           :   IN    std_logic;
          rd_addr                         :   IN    std_logic_vector(AddrWidth - 1 DOWNTO 0);  -- generic width
          rd_dout                         :   OUT   std_logic_vector(DataWidth - 1 DOWNTO 0)  -- generic width
          );
  END COMPONENT;

  -- Component Configuration Statements
  FOR ALL : SimpleDualPortRAM_generic
    USE ENTITY work.SimpleDualPortRAM_generic(rtl);

  -- Signals
  SIGNAL wrStateMachineBitNatural_wrState : unsigned(1 DOWNTO 0);  -- ufix2
  SIGNAL wrStateMachineBitNatural_wrAddrCnt : unsigned(9 DOWNTO 0);  -- ufix10
  SIGNAL wrStateMachineBitNatural_wrState_next : unsigned(1 DOWNTO 0);  -- ufix2
  SIGNAL wrStateMachineBitNatural_wrAddrCnt_next : unsigned(9 DOWNTO 0);  -- ufix10
  SIGNAL WrEnb                            : std_logic;
  SIGNAL wrAddr                           : unsigned(9 DOWNTO 0);  -- ufix10
  SIGNAL sampleIdx                        : unsigned(9 DOWNTO 0);  -- ufix10
  SIGNAL rdAddr                           : unsigned(9 DOWNTO 0);  -- ufix10
  SIGNAL memOut_im                        : std_logic_vector(25 DOWNTO 0);  -- ufix26
  SIGNAL memOut_im_signed                 : signed(25 DOWNTO 0);  -- sfix26_En14
  SIGNAL memOut_re                        : std_logic_vector(25 DOWNTO 0);  -- ufix26
  SIGNAL memOut_re_signed                 : signed(25 DOWNTO 0);  -- sfix26_En14
  SIGNAL rdStateMachineBitNatural_rdState : unsigned(1 DOWNTO 0);  -- ufix2
  SIGNAL rdStateMachineBitNatural_rdAddrCnt : unsigned(9 DOWNTO 0);  -- ufix10
  SIGNAL rdStateMachineBitNatural_doutVldReg1 : std_logic;
  SIGNAL rdStateMachineBitNatural_doutVldReg2 : std_logic;
  SIGNAL rdStateMachineBitNatural_doutReReg : signed(25 DOWNTO 0);  -- sfix26
  SIGNAL rdStateMachineBitNatural_doutImReg : signed(25 DOWNTO 0);  -- sfix26
  SIGNAL rdStateMachineBitNatural_rdState_next : unsigned(1 DOWNTO 0);  -- ufix2
  SIGNAL rdStateMachineBitNatural_rdAddrCnt_next : unsigned(9 DOWNTO 0);  -- ufix10
  SIGNAL rdStateMachineBitNatural_doutVldReg1_next : std_logic;
  SIGNAL rdStateMachineBitNatural_doutVldReg2_next : std_logic;
  SIGNAL rdStateMachineBitNatural_doutReReg_next : signed(25 DOWNTO 0);  -- sfix26_En14
  SIGNAL rdStateMachineBitNatural_doutImReg_next : signed(25 DOWNTO 0);  -- sfix26_En14
  SIGNAL dout_re1_tmp                     : signed(25 DOWNTO 0);  -- sfix26_En14
  SIGNAL dout_im1_tmp                     : signed(25 DOWNTO 0);  -- sfix26_En14

BEGIN
  u_dataMEM_im_1 : SimpleDualPortRAM_generic
    GENERIC MAP( AddrWidth => 10,
                 DataWidth => 26
                 )
    PORT MAP( clk => clk,
              enb => enb,
              wr_din => dout_10_1_im,
              wr_addr => std_logic_vector(wrAddr),
              wr_en => WrEnb,
              rd_addr => std_logic_vector(rdAddr),
              rd_dout => memOut_im
              );

  u_dataMEM_re_1 : SimpleDualPortRAM_generic
    GENERIC MAP( AddrWidth => 10,
                 DataWidth => 26
                 )
    PORT MAP( clk => clk,
              enb => enb,
              wr_din => dout_10_1_re,
              wr_addr => std_logic_vector(wrAddr),
              wr_en => WrEnb,
              rd_addr => std_logic_vector(rdAddr),
              rd_dout => memOut_re
              );

  -- wrStateMachineBitNatural
  wrStateMachineBitNatural_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      wrStateMachineBitNatural_wrState <= to_unsigned(16#0#, 2);
      wrStateMachineBitNatural_wrAddrCnt <= to_unsigned(16#000#, 10);
    ELSIF clk'EVENT AND clk = '1' THEN
      IF enb = '1' THEN
        wrStateMachineBitNatural_wrState <= wrStateMachineBitNatural_wrState_next;
        wrStateMachineBitNatural_wrAddrCnt <= wrStateMachineBitNatural_wrAddrCnt_next;
      END IF;
    END IF;
  END PROCESS wrStateMachineBitNatural_process;

  wrStateMachineBitNatural_output : PROCESS (wrStateMachineBitNatural_wrState, wrStateMachineBitNatural_wrAddrCnt,
       dout_10_1_vld)
  BEGIN
    wrStateMachineBitNatural_wrState_next <= wrStateMachineBitNatural_wrState;
    wrStateMachineBitNatural_wrAddrCnt_next <= wrStateMachineBitNatural_wrAddrCnt;
    IF wrStateMachineBitNatural_wrState = to_unsigned(16#2#, 2) THEN 
      wrAddr <= unsigned'(wrStateMachineBitNatural_wrAddrCnt(0) & wrStateMachineBitNatural_wrAddrCnt(1) & wrStateMachineBitNatural_wrAddrCnt(2) & wrStateMachineBitNatural_wrAddrCnt(3) & wrStateMachineBitNatural_wrAddrCnt(4) & wrStateMachineBitNatural_wrAddrCnt(5) & wrStateMachineBitNatural_wrAddrCnt(6) & wrStateMachineBitNatural_wrAddrCnt(7) & wrStateMachineBitNatural_wrAddrCnt(8) & wrStateMachineBitNatural_wrAddrCnt(9));
    ELSE 
      wrAddr <= wrStateMachineBitNatural_wrAddrCnt;
    END IF;
    CASE wrStateMachineBitNatural_wrState IS
      WHEN "00" =>
        IF dout_10_1_vld = '1' THEN 
          wrStateMachineBitNatural_wrState_next <= to_unsigned(16#1#, 2);
          wrStateMachineBitNatural_wrAddrCnt_next <= to_unsigned(16#001#, 10);
        ELSE 
          wrStateMachineBitNatural_wrState_next <= to_unsigned(16#0#, 2);
          wrStateMachineBitNatural_wrAddrCnt_next <= to_unsigned(16#000#, 10);
        END IF;
      WHEN "01" =>
        IF dout_10_1_vld = '1' THEN 
          IF wrStateMachineBitNatural_wrAddrCnt = to_unsigned(16#3FF#, 10) THEN 
            wrStateMachineBitNatural_wrAddrCnt_next <= to_unsigned(16#000#, 10);
            wrStateMachineBitNatural_wrState_next <= to_unsigned(16#2#, 2);
          ELSE 
            wrStateMachineBitNatural_wrAddrCnt_next <= wrStateMachineBitNatural_wrAddrCnt + to_unsigned(16#001#, 10);
            wrStateMachineBitNatural_wrState_next <= to_unsigned(16#1#, 2);
          END IF;
        END IF;
      WHEN "10" =>
        IF dout_10_1_vld = '1' THEN 
          IF wrStateMachineBitNatural_wrAddrCnt = to_unsigned(16#3FF#, 10) THEN 
            wrStateMachineBitNatural_wrAddrCnt_next <= to_unsigned(16#000#, 10);
            wrStateMachineBitNatural_wrState_next <= to_unsigned(16#1#, 2);
          ELSE 
            wrStateMachineBitNatural_wrAddrCnt_next <= wrStateMachineBitNatural_wrAddrCnt + to_unsigned(16#001#, 10);
            wrStateMachineBitNatural_wrState_next <= to_unsigned(16#2#, 2);
          END IF;
        END IF;
      WHEN OTHERS => 
        wrStateMachineBitNatural_wrState_next <= to_unsigned(16#0#, 2);
        wrStateMachineBitNatural_wrAddrCnt_next <= to_unsigned(16#000#, 10);
    END CASE;
    WrEnb <= dout_10_1_vld;
    sampleIdx <= wrStateMachineBitNatural_wrAddrCnt;
  END PROCESS wrStateMachineBitNatural_output;


  memOut_im_signed <= signed(memOut_im);

  memOut_re_signed <= signed(memOut_re);

  -- rdStateMachineBitNatural
  rdStateMachineBitNatural_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      rdStateMachineBitNatural_rdState <= to_unsigned(16#0#, 2);
      rdStateMachineBitNatural_rdAddrCnt <= to_unsigned(16#000#, 10);
      rdStateMachineBitNatural_doutVldReg1 <= '0';
      rdStateMachineBitNatural_doutVldReg2 <= '0';
      rdStateMachineBitNatural_doutReReg <= to_signed(16#0000000#, 26);
      rdStateMachineBitNatural_doutImReg <= to_signed(16#0000000#, 26);
    ELSIF clk'EVENT AND clk = '1' THEN
      IF enb = '1' THEN
        rdStateMachineBitNatural_rdState <= rdStateMachineBitNatural_rdState_next;
        rdStateMachineBitNatural_rdAddrCnt <= rdStateMachineBitNatural_rdAddrCnt_next;
        rdStateMachineBitNatural_doutVldReg1 <= rdStateMachineBitNatural_doutVldReg1_next;
        rdStateMachineBitNatural_doutVldReg2 <= rdStateMachineBitNatural_doutVldReg2_next;
        rdStateMachineBitNatural_doutReReg <= rdStateMachineBitNatural_doutReReg_next;
        rdStateMachineBitNatural_doutImReg <= rdStateMachineBitNatural_doutImReg_next;
      END IF;
    END IF;
  END PROCESS rdStateMachineBitNatural_process;

  rdStateMachineBitNatural_output : PROCESS (rdStateMachineBitNatural_rdState, rdStateMachineBitNatural_rdAddrCnt,
       rdStateMachineBitNatural_doutVldReg1,
       rdStateMachineBitNatural_doutVldReg2, rdStateMachineBitNatural_doutReReg,
       rdStateMachineBitNatural_doutImReg, sampleIdx, memOut_re_signed,
       memOut_im_signed)
  BEGIN
    rdStateMachineBitNatural_rdState_next <= rdStateMachineBitNatural_rdState;
    rdStateMachineBitNatural_rdAddrCnt_next <= rdStateMachineBitNatural_rdAddrCnt;
    rdStateMachineBitNatural_doutReReg_next <= rdStateMachineBitNatural_doutReReg;
    rdStateMachineBitNatural_doutImReg_next <= rdStateMachineBitNatural_doutImReg;
    IF rdStateMachineBitNatural_rdState = to_unsigned(16#1#, 2) THEN 
      rdAddr <= unsigned'(rdStateMachineBitNatural_rdAddrCnt(0) & rdStateMachineBitNatural_rdAddrCnt(1) & rdStateMachineBitNatural_rdAddrCnt(2) & rdStateMachineBitNatural_rdAddrCnt(3) & rdStateMachineBitNatural_rdAddrCnt(4) & rdStateMachineBitNatural_rdAddrCnt(5) & rdStateMachineBitNatural_rdAddrCnt(6) & rdStateMachineBitNatural_rdAddrCnt(7) & rdStateMachineBitNatural_rdAddrCnt(8) & rdStateMachineBitNatural_rdAddrCnt(9));
    ELSE 
      rdAddr <= rdStateMachineBitNatural_rdAddrCnt;
    END IF;
    CASE rdStateMachineBitNatural_rdState IS
      WHEN "00" =>
        rdStateMachineBitNatural_doutVldReg1_next <= '0';
        IF sampleIdx >= to_unsigned(16#3DD#, 10) THEN 
          rdStateMachineBitNatural_rdAddrCnt_next <= to_unsigned(16#001#, 10);
          rdStateMachineBitNatural_doutVldReg1_next <= '1';
          rdStateMachineBitNatural_rdState_next <= to_unsigned(16#1#, 2);
        ELSE 
          rdStateMachineBitNatural_rdAddrCnt_next <= to_unsigned(16#000#, 10);
          rdStateMachineBitNatural_rdState_next <= to_unsigned(16#0#, 2);
        END IF;
      WHEN "01" =>
        rdStateMachineBitNatural_doutVldReg1_next <= '1';
        IF rdStateMachineBitNatural_rdAddrCnt = to_unsigned(16#3FF#, 10) THEN 
          rdStateMachineBitNatural_rdAddrCnt_next <= to_unsigned(16#000#, 10);
          rdStateMachineBitNatural_rdState_next <= to_unsigned(16#2#, 2);
        ELSE 
          rdStateMachineBitNatural_rdAddrCnt_next <= rdStateMachineBitNatural_rdAddrCnt + to_unsigned(16#001#, 10);
          rdStateMachineBitNatural_rdState_next <= to_unsigned(16#1#, 2);
        END IF;
      WHEN "10" =>
        rdStateMachineBitNatural_doutVldReg1_next <= '0';
        IF sampleIdx >= to_unsigned(16#3DD#, 10) THEN 
          rdStateMachineBitNatural_rdAddrCnt_next <= to_unsigned(16#001#, 10);
          rdStateMachineBitNatural_doutVldReg1_next <= '1';
          rdStateMachineBitNatural_rdState_next <= to_unsigned(16#3#, 2);
        ELSE 
          rdStateMachineBitNatural_rdAddrCnt_next <= to_unsigned(16#000#, 10);
          rdStateMachineBitNatural_rdState_next <= to_unsigned(16#2#, 2);
        END IF;
      WHEN "11" =>
        rdStateMachineBitNatural_doutVldReg1_next <= '1';
        IF rdStateMachineBitNatural_rdAddrCnt = to_unsigned(16#3FF#, 10) THEN 
          rdStateMachineBitNatural_rdAddrCnt_next <= to_unsigned(16#000#, 10);
          rdStateMachineBitNatural_rdState_next <= to_unsigned(16#0#, 2);
        ELSE 
          rdStateMachineBitNatural_rdAddrCnt_next <= rdStateMachineBitNatural_rdAddrCnt + to_unsigned(16#001#, 10);
          rdStateMachineBitNatural_rdState_next <= to_unsigned(16#3#, 2);
        END IF;
      WHEN OTHERS => 
        rdStateMachineBitNatural_rdState_next <= to_unsigned(16#0#, 2);
        rdStateMachineBitNatural_rdAddrCnt_next <= to_unsigned(16#000#, 10);
        rdStateMachineBitNatural_doutVldReg1_next <= '0';
    END CASE;
    IF rdStateMachineBitNatural_doutVldReg1 = '1' THEN 
      rdStateMachineBitNatural_doutReReg_next <= memOut_re_signed;
      rdStateMachineBitNatural_doutImReg_next <= memOut_im_signed;
    END IF;
    rdStateMachineBitNatural_doutVldReg2_next <= rdStateMachineBitNatural_doutVldReg1;
    dout_re1_tmp <= rdStateMachineBitNatural_doutReReg;
    dout_im1_tmp <= rdStateMachineBitNatural_doutImReg;
    dout_vld1 <= rdStateMachineBitNatural_doutVldReg2;
  END PROCESS rdStateMachineBitNatural_output;


  dout_re1 <= std_logic_vector(dout_re1_tmp);

  dout_im1 <= std_logic_vector(dout_im1_tmp);

END rtl;

