# This script is generated when there are blocks with ResetType property set to None.
# This script initializes registers or signals generated from these blocks before
# the start of simulation, as they do not have a reset port or are not initialized in the HDL code.
# The initialization commands are compatible with ModelSim. Other simulation tools may use different syntax.
# For VHDL, the command syntax is: 
# force -deposit <path to signal> <value to initialize to> <time to initialize at> 
# 
# For Verilog, the command syntax is: 
# change <path to signal> <value to initialize to> 
force -deposit ${::dut_prefix}Subsystem/u_FFT_HDL_Optimized/u_SDF1_3_1/u_MUL3/Complex3Multiply_din1_re_pipe1 0 1
force -deposit ${::dut_prefix}Subsystem/u_FFT_HDL_Optimized/u_SDF1_3_1/u_MUL3/Complex3Multiply_din1_im_pipe1 0 1
force -deposit ${::dut_prefix}Subsystem/u_FFT_HDL_Optimized/u_SDF1_3_1/u_MUL3/Complex3Multiply_din1_sum_pipe1 0 1
force -deposit ${::dut_prefix}Subsystem/u_FFT_HDL_Optimized/u_SDF1_3_1/u_MUL3/Complex3Multiply_twiddle_re_pipe1 0 1
force -deposit ${::dut_prefix}Subsystem/u_FFT_HDL_Optimized/u_SDF1_3_1/u_MUL3/Complex3Multiply_twiddle_im_pipe1 0 1
force -deposit ${::dut_prefix}Subsystem/u_FFT_HDL_Optimized/u_SDF1_3_1/u_MUL3/Complex3Multiply_twiddle_sum_pipe1 0 1
force -deposit ${::dut_prefix}Subsystem/u_FFT_HDL_Optimized/u_SDF1_3_1/u_MUL3/Complex3Multiply_prodOfRe_pipe1 0 1
force -deposit ${::dut_prefix}Subsystem/u_FFT_HDL_Optimized/u_SDF1_3_1/u_MUL3/Complex3Multiply_ProdOfIm_pipe1 0 1
force -deposit ${::dut_prefix}Subsystem/u_FFT_HDL_Optimized/u_SDF1_3_1/u_MUL3/Complex3Multiply_prodOfSum_pipe1 0 1
force -deposit ${::dut_prefix}Subsystem/u_FFT_HDL_Optimized/u_SDF1_3_1/u_MUL3/prodOfRe 0 1
force -deposit ${::dut_prefix}Subsystem/u_FFT_HDL_Optimized/u_SDF1_3_1/u_MUL3/prodOfIm 0 1
force -deposit ${::dut_prefix}Subsystem/u_FFT_HDL_Optimized/u_SDF1_3_1/u_MUL3/prodOfSum 0 1
force -deposit ${::dut_prefix}Subsystem/u_FFT_HDL_Optimized/u_SDF1_5_1/u_MUL3/Complex3Multiply_din1_re_pipe1 0 1
force -deposit ${::dut_prefix}Subsystem/u_FFT_HDL_Optimized/u_SDF1_5_1/u_MUL3/Complex3Multiply_din1_im_pipe1 0 1
force -deposit ${::dut_prefix}Subsystem/u_FFT_HDL_Optimized/u_SDF1_5_1/u_MUL3/Complex3Multiply_din1_sum_pipe1 0 1
force -deposit ${::dut_prefix}Subsystem/u_FFT_HDL_Optimized/u_SDF1_5_1/u_MUL3/Complex3Multiply_twiddle_re_pipe1 0 1
force -deposit ${::dut_prefix}Subsystem/u_FFT_HDL_Optimized/u_SDF1_5_1/u_MUL3/Complex3Multiply_twiddle_im_pipe1 0 1
force -deposit ${::dut_prefix}Subsystem/u_FFT_HDL_Optimized/u_SDF1_5_1/u_MUL3/Complex3Multiply_twiddle_sum_pipe1 0 1
force -deposit ${::dut_prefix}Subsystem/u_FFT_HDL_Optimized/u_SDF1_5_1/u_MUL3/Complex3Multiply_prodOfRe_pipe1 0 1
force -deposit ${::dut_prefix}Subsystem/u_FFT_HDL_Optimized/u_SDF1_5_1/u_MUL3/Complex3Multiply_ProdOfIm_pipe1 0 1
force -deposit ${::dut_prefix}Subsystem/u_FFT_HDL_Optimized/u_SDF1_5_1/u_MUL3/Complex3Multiply_prodOfSum_pipe1 0 1
force -deposit ${::dut_prefix}Subsystem/u_FFT_HDL_Optimized/u_SDF1_5_1/u_MUL3/prodOfRe 0 1
force -deposit ${::dut_prefix}Subsystem/u_FFT_HDL_Optimized/u_SDF1_5_1/u_MUL3/prodOfIm 0 1
force -deposit ${::dut_prefix}Subsystem/u_FFT_HDL_Optimized/u_SDF1_5_1/u_MUL3/prodOfSum 0 1
force -deposit ${::dut_prefix}Subsystem/u_FFT_HDL_Optimized/u_SDF1_7_1/u_MUL3/Complex3Multiply_din1_re_pipe1 0 1
force -deposit ${::dut_prefix}Subsystem/u_FFT_HDL_Optimized/u_SDF1_7_1/u_MUL3/Complex3Multiply_din1_im_pipe1 0 1
force -deposit ${::dut_prefix}Subsystem/u_FFT_HDL_Optimized/u_SDF1_7_1/u_MUL3/Complex3Multiply_din1_sum_pipe1 0 1
force -deposit ${::dut_prefix}Subsystem/u_FFT_HDL_Optimized/u_SDF1_7_1/u_MUL3/Complex3Multiply_twiddle_re_pipe1 0 1
force -deposit ${::dut_prefix}Subsystem/u_FFT_HDL_Optimized/u_SDF1_7_1/u_MUL3/Complex3Multiply_twiddle_im_pipe1 0 1
force -deposit ${::dut_prefix}Subsystem/u_FFT_HDL_Optimized/u_SDF1_7_1/u_MUL3/Complex3Multiply_twiddle_sum_pipe1 0 1
force -deposit ${::dut_prefix}Subsystem/u_FFT_HDL_Optimized/u_SDF1_7_1/u_MUL3/Complex3Multiply_prodOfRe_pipe1 0 1
force -deposit ${::dut_prefix}Subsystem/u_FFT_HDL_Optimized/u_SDF1_7_1/u_MUL3/Complex3Multiply_ProdOfIm_pipe1 0 1
force -deposit ${::dut_prefix}Subsystem/u_FFT_HDL_Optimized/u_SDF1_7_1/u_MUL3/Complex3Multiply_prodOfSum_pipe1 0 1
force -deposit ${::dut_prefix}Subsystem/u_FFT_HDL_Optimized/u_SDF1_7_1/u_MUL3/prodOfRe 0 1
force -deposit ${::dut_prefix}Subsystem/u_FFT_HDL_Optimized/u_SDF1_7_1/u_MUL3/prodOfIm 0 1
force -deposit ${::dut_prefix}Subsystem/u_FFT_HDL_Optimized/u_SDF1_7_1/u_MUL3/prodOfSum 0 1
force -deposit ${::dut_prefix}Subsystem/u_FFT_HDL_Optimized/u_SDF1_9_1/u_MUL3/Complex3Multiply_din1_re_pipe1 0 1
force -deposit ${::dut_prefix}Subsystem/u_FFT_HDL_Optimized/u_SDF1_9_1/u_MUL3/Complex3Multiply_din1_im_pipe1 0 1
force -deposit ${::dut_prefix}Subsystem/u_FFT_HDL_Optimized/u_SDF1_9_1/u_MUL3/Complex3Multiply_din1_sum_pipe1 0 1
force -deposit ${::dut_prefix}Subsystem/u_FFT_HDL_Optimized/u_SDF1_9_1/u_MUL3/Complex3Multiply_twiddle_re_pipe1 0 1
force -deposit ${::dut_prefix}Subsystem/u_FFT_HDL_Optimized/u_SDF1_9_1/u_MUL3/Complex3Multiply_twiddle_im_pipe1 0 1
force -deposit ${::dut_prefix}Subsystem/u_FFT_HDL_Optimized/u_SDF1_9_1/u_MUL3/Complex3Multiply_twiddle_sum_pipe1 0 1
force -deposit ${::dut_prefix}Subsystem/u_FFT_HDL_Optimized/u_SDF1_9_1/u_MUL3/Complex3Multiply_prodOfRe_pipe1 0 1
force -deposit ${::dut_prefix}Subsystem/u_FFT_HDL_Optimized/u_SDF1_9_1/u_MUL3/Complex3Multiply_ProdOfIm_pipe1 0 1
force -deposit ${::dut_prefix}Subsystem/u_FFT_HDL_Optimized/u_SDF1_9_1/u_MUL3/Complex3Multiply_prodOfSum_pipe1 0 1
force -deposit ${::dut_prefix}Subsystem/u_FFT_HDL_Optimized/u_SDF1_9_1/u_MUL3/prodOfRe 0 1
force -deposit ${::dut_prefix}Subsystem/u_FFT_HDL_Optimized/u_SDF1_9_1/u_MUL3/prodOfIm 0 1
force -deposit ${::dut_prefix}Subsystem/u_FFT_HDL_Optimized/u_SDF1_9_1/u_MUL3/prodOfSum 0 1
force -deposit ${::dut_prefix}Subsystem/u_FFT_HDL_Optimized1/u_SDF1_3_1/u_MUL3/Complex3Multiply_din1_re_pipe1 0 1
force -deposit ${::dut_prefix}Subsystem/u_FFT_HDL_Optimized1/u_SDF1_3_1/u_MUL3/Complex3Multiply_din1_im_pipe1 0 1
force -deposit ${::dut_prefix}Subsystem/u_FFT_HDL_Optimized1/u_SDF1_3_1/u_MUL3/Complex3Multiply_din1_sum_pipe1 0 1
force -deposit ${::dut_prefix}Subsystem/u_FFT_HDL_Optimized1/u_SDF1_3_1/u_MUL3/Complex3Multiply_twiddle_re_pipe1 0 1
force -deposit ${::dut_prefix}Subsystem/u_FFT_HDL_Optimized1/u_SDF1_3_1/u_MUL3/Complex3Multiply_twiddle_im_pipe1 0 1
force -deposit ${::dut_prefix}Subsystem/u_FFT_HDL_Optimized1/u_SDF1_3_1/u_MUL3/Complex3Multiply_twiddle_sum_pipe1 0 1
force -deposit ${::dut_prefix}Subsystem/u_FFT_HDL_Optimized1/u_SDF1_3_1/u_MUL3/Complex3Multiply_prodOfRe_pipe1 0 1
force -deposit ${::dut_prefix}Subsystem/u_FFT_HDL_Optimized1/u_SDF1_3_1/u_MUL3/Complex3Multiply_ProdOfIm_pipe1 0 1
force -deposit ${::dut_prefix}Subsystem/u_FFT_HDL_Optimized1/u_SDF1_3_1/u_MUL3/Complex3Multiply_prodOfSum_pipe1 0 1
force -deposit ${::dut_prefix}Subsystem/u_FFT_HDL_Optimized1/u_SDF1_3_1/u_MUL3/prodOfRe 0 1
force -deposit ${::dut_prefix}Subsystem/u_FFT_HDL_Optimized1/u_SDF1_3_1/u_MUL3/prodOfIm 0 1
force -deposit ${::dut_prefix}Subsystem/u_FFT_HDL_Optimized1/u_SDF1_3_1/u_MUL3/prodOfSum 0 1
force -deposit ${::dut_prefix}Subsystem/u_FFT_HDL_Optimized1/u_SDF1_5_1/u_MUL3/Complex3Multiply_din1_re_pipe1 0 1
force -deposit ${::dut_prefix}Subsystem/u_FFT_HDL_Optimized1/u_SDF1_5_1/u_MUL3/Complex3Multiply_din1_im_pipe1 0 1
force -deposit ${::dut_prefix}Subsystem/u_FFT_HDL_Optimized1/u_SDF1_5_1/u_MUL3/Complex3Multiply_din1_sum_pipe1 0 1
force -deposit ${::dut_prefix}Subsystem/u_FFT_HDL_Optimized1/u_SDF1_5_1/u_MUL3/Complex3Multiply_twiddle_re_pipe1 0 1
force -deposit ${::dut_prefix}Subsystem/u_FFT_HDL_Optimized1/u_SDF1_5_1/u_MUL3/Complex3Multiply_twiddle_im_pipe1 0 1
force -deposit ${::dut_prefix}Subsystem/u_FFT_HDL_Optimized1/u_SDF1_5_1/u_MUL3/Complex3Multiply_twiddle_sum_pipe1 0 1
force -deposit ${::dut_prefix}Subsystem/u_FFT_HDL_Optimized1/u_SDF1_5_1/u_MUL3/Complex3Multiply_prodOfRe_pipe1 0 1
force -deposit ${::dut_prefix}Subsystem/u_FFT_HDL_Optimized1/u_SDF1_5_1/u_MUL3/Complex3Multiply_ProdOfIm_pipe1 0 1
force -deposit ${::dut_prefix}Subsystem/u_FFT_HDL_Optimized1/u_SDF1_5_1/u_MUL3/Complex3Multiply_prodOfSum_pipe1 0 1
force -deposit ${::dut_prefix}Subsystem/u_FFT_HDL_Optimized1/u_SDF1_5_1/u_MUL3/prodOfRe 0 1
force -deposit ${::dut_prefix}Subsystem/u_FFT_HDL_Optimized1/u_SDF1_5_1/u_MUL3/prodOfIm 0 1
force -deposit ${::dut_prefix}Subsystem/u_FFT_HDL_Optimized1/u_SDF1_5_1/u_MUL3/prodOfSum 0 1
force -deposit ${::dut_prefix}Subsystem/u_FFT_HDL_Optimized1/u_SDF1_7_1/u_MUL3/Complex3Multiply_din1_re_pipe1 0 1
force -deposit ${::dut_prefix}Subsystem/u_FFT_HDL_Optimized1/u_SDF1_7_1/u_MUL3/Complex3Multiply_din1_im_pipe1 0 1
force -deposit ${::dut_prefix}Subsystem/u_FFT_HDL_Optimized1/u_SDF1_7_1/u_MUL3/Complex3Multiply_din1_sum_pipe1 0 1
force -deposit ${::dut_prefix}Subsystem/u_FFT_HDL_Optimized1/u_SDF1_7_1/u_MUL3/Complex3Multiply_twiddle_re_pipe1 0 1
force -deposit ${::dut_prefix}Subsystem/u_FFT_HDL_Optimized1/u_SDF1_7_1/u_MUL3/Complex3Multiply_twiddle_im_pipe1 0 1
force -deposit ${::dut_prefix}Subsystem/u_FFT_HDL_Optimized1/u_SDF1_7_1/u_MUL3/Complex3Multiply_twiddle_sum_pipe1 0 1
force -deposit ${::dut_prefix}Subsystem/u_FFT_HDL_Optimized1/u_SDF1_7_1/u_MUL3/Complex3Multiply_prodOfRe_pipe1 0 1
force -deposit ${::dut_prefix}Subsystem/u_FFT_HDL_Optimized1/u_SDF1_7_1/u_MUL3/Complex3Multiply_ProdOfIm_pipe1 0 1
force -deposit ${::dut_prefix}Subsystem/u_FFT_HDL_Optimized1/u_SDF1_7_1/u_MUL3/Complex3Multiply_prodOfSum_pipe1 0 1
force -deposit ${::dut_prefix}Subsystem/u_FFT_HDL_Optimized1/u_SDF1_7_1/u_MUL3/prodOfRe 0 1
force -deposit ${::dut_prefix}Subsystem/u_FFT_HDL_Optimized1/u_SDF1_7_1/u_MUL3/prodOfIm 0 1
force -deposit ${::dut_prefix}Subsystem/u_FFT_HDL_Optimized1/u_SDF1_7_1/u_MUL3/prodOfSum 0 1
force -deposit ${::dut_prefix}Subsystem/u_FFT_HDL_Optimized1/u_SDF1_9_1/u_MUL3/Complex3Multiply_din1_re_pipe1 0 1
force -deposit ${::dut_prefix}Subsystem/u_FFT_HDL_Optimized1/u_SDF1_9_1/u_MUL3/Complex3Multiply_din1_im_pipe1 0 1
force -deposit ${::dut_prefix}Subsystem/u_FFT_HDL_Optimized1/u_SDF1_9_1/u_MUL3/Complex3Multiply_din1_sum_pipe1 0 1
force -deposit ${::dut_prefix}Subsystem/u_FFT_HDL_Optimized1/u_SDF1_9_1/u_MUL3/Complex3Multiply_twiddle_re_pipe1 0 1
force -deposit ${::dut_prefix}Subsystem/u_FFT_HDL_Optimized1/u_SDF1_9_1/u_MUL3/Complex3Multiply_twiddle_im_pipe1 0 1
force -deposit ${::dut_prefix}Subsystem/u_FFT_HDL_Optimized1/u_SDF1_9_1/u_MUL3/Complex3Multiply_twiddle_sum_pipe1 0 1
force -deposit ${::dut_prefix}Subsystem/u_FFT_HDL_Optimized1/u_SDF1_9_1/u_MUL3/Complex3Multiply_prodOfRe_pipe1 0 1
force -deposit ${::dut_prefix}Subsystem/u_FFT_HDL_Optimized1/u_SDF1_9_1/u_MUL3/Complex3Multiply_ProdOfIm_pipe1 0 1
force -deposit ${::dut_prefix}Subsystem/u_FFT_HDL_Optimized1/u_SDF1_9_1/u_MUL3/Complex3Multiply_prodOfSum_pipe1 0 1
force -deposit ${::dut_prefix}Subsystem/u_FFT_HDL_Optimized1/u_SDF1_9_1/u_MUL3/prodOfRe 0 1
force -deposit ${::dut_prefix}Subsystem/u_FFT_HDL_Optimized1/u_SDF1_9_1/u_MUL3/prodOfIm 0 1
force -deposit ${::dut_prefix}Subsystem/u_FFT_HDL_Optimized1/u_SDF1_9_1/u_MUL3/prodOfSum 0 1
force -deposit ${::dut_prefix}Subsystem/u_FFT_HDL_Optimized2/u_SDF1_3_1/u_MUL3/Complex3Multiply_din1_re_pipe1 0 1
force -deposit ${::dut_prefix}Subsystem/u_FFT_HDL_Optimized2/u_SDF1_3_1/u_MUL3/Complex3Multiply_din1_im_pipe1 0 1
force -deposit ${::dut_prefix}Subsystem/u_FFT_HDL_Optimized2/u_SDF1_3_1/u_MUL3/Complex3Multiply_din1_sum_pipe1 0 1
force -deposit ${::dut_prefix}Subsystem/u_FFT_HDL_Optimized2/u_SDF1_3_1/u_MUL3/Complex3Multiply_twiddle_re_pipe1 0 1
force -deposit ${::dut_prefix}Subsystem/u_FFT_HDL_Optimized2/u_SDF1_3_1/u_MUL3/Complex3Multiply_twiddle_im_pipe1 0 1
force -deposit ${::dut_prefix}Subsystem/u_FFT_HDL_Optimized2/u_SDF1_3_1/u_MUL3/Complex3Multiply_twiddle_sum_pipe1 0 1
force -deposit ${::dut_prefix}Subsystem/u_FFT_HDL_Optimized2/u_SDF1_3_1/u_MUL3/Complex3Multiply_prodOfRe_pipe1 0 1
force -deposit ${::dut_prefix}Subsystem/u_FFT_HDL_Optimized2/u_SDF1_3_1/u_MUL3/Complex3Multiply_ProdOfIm_pipe1 0 1
force -deposit ${::dut_prefix}Subsystem/u_FFT_HDL_Optimized2/u_SDF1_3_1/u_MUL3/Complex3Multiply_prodOfSum_pipe1 0 1
force -deposit ${::dut_prefix}Subsystem/u_FFT_HDL_Optimized2/u_SDF1_3_1/u_MUL3/prodOfRe 0 1
force -deposit ${::dut_prefix}Subsystem/u_FFT_HDL_Optimized2/u_SDF1_3_1/u_MUL3/prodOfIm 0 1
force -deposit ${::dut_prefix}Subsystem/u_FFT_HDL_Optimized2/u_SDF1_3_1/u_MUL3/prodOfSum 0 1
force -deposit ${::dut_prefix}Subsystem/u_FFT_HDL_Optimized2/u_SDF1_5_1/u_MUL3/Complex3Multiply_din1_re_pipe1 0 1
force -deposit ${::dut_prefix}Subsystem/u_FFT_HDL_Optimized2/u_SDF1_5_1/u_MUL3/Complex3Multiply_din1_im_pipe1 0 1
force -deposit ${::dut_prefix}Subsystem/u_FFT_HDL_Optimized2/u_SDF1_5_1/u_MUL3/Complex3Multiply_din1_sum_pipe1 0 1
force -deposit ${::dut_prefix}Subsystem/u_FFT_HDL_Optimized2/u_SDF1_5_1/u_MUL3/Complex3Multiply_twiddle_re_pipe1 0 1
force -deposit ${::dut_prefix}Subsystem/u_FFT_HDL_Optimized2/u_SDF1_5_1/u_MUL3/Complex3Multiply_twiddle_im_pipe1 0 1
force -deposit ${::dut_prefix}Subsystem/u_FFT_HDL_Optimized2/u_SDF1_5_1/u_MUL3/Complex3Multiply_twiddle_sum_pipe1 0 1
force -deposit ${::dut_prefix}Subsystem/u_FFT_HDL_Optimized2/u_SDF1_5_1/u_MUL3/Complex3Multiply_prodOfRe_pipe1 0 1
force -deposit ${::dut_prefix}Subsystem/u_FFT_HDL_Optimized2/u_SDF1_5_1/u_MUL3/Complex3Multiply_ProdOfIm_pipe1 0 1
force -deposit ${::dut_prefix}Subsystem/u_FFT_HDL_Optimized2/u_SDF1_5_1/u_MUL3/Complex3Multiply_prodOfSum_pipe1 0 1
force -deposit ${::dut_prefix}Subsystem/u_FFT_HDL_Optimized2/u_SDF1_5_1/u_MUL3/prodOfRe 0 1
force -deposit ${::dut_prefix}Subsystem/u_FFT_HDL_Optimized2/u_SDF1_5_1/u_MUL3/prodOfIm 0 1
force -deposit ${::dut_prefix}Subsystem/u_FFT_HDL_Optimized2/u_SDF1_5_1/u_MUL3/prodOfSum 0 1
force -deposit ${::dut_prefix}Subsystem/u_FFT_HDL_Optimized2/u_SDF1_7_1/u_MUL3/Complex3Multiply_din1_re_pipe1 0 1
force -deposit ${::dut_prefix}Subsystem/u_FFT_HDL_Optimized2/u_SDF1_7_1/u_MUL3/Complex3Multiply_din1_im_pipe1 0 1
force -deposit ${::dut_prefix}Subsystem/u_FFT_HDL_Optimized2/u_SDF1_7_1/u_MUL3/Complex3Multiply_din1_sum_pipe1 0 1
force -deposit ${::dut_prefix}Subsystem/u_FFT_HDL_Optimized2/u_SDF1_7_1/u_MUL3/Complex3Multiply_twiddle_re_pipe1 0 1
force -deposit ${::dut_prefix}Subsystem/u_FFT_HDL_Optimized2/u_SDF1_7_1/u_MUL3/Complex3Multiply_twiddle_im_pipe1 0 1
force -deposit ${::dut_prefix}Subsystem/u_FFT_HDL_Optimized2/u_SDF1_7_1/u_MUL3/Complex3Multiply_twiddle_sum_pipe1 0 1
force -deposit ${::dut_prefix}Subsystem/u_FFT_HDL_Optimized2/u_SDF1_7_1/u_MUL3/Complex3Multiply_prodOfRe_pipe1 0 1
force -deposit ${::dut_prefix}Subsystem/u_FFT_HDL_Optimized2/u_SDF1_7_1/u_MUL3/Complex3Multiply_ProdOfIm_pipe1 0 1
force -deposit ${::dut_prefix}Subsystem/u_FFT_HDL_Optimized2/u_SDF1_7_1/u_MUL3/Complex3Multiply_prodOfSum_pipe1 0 1
force -deposit ${::dut_prefix}Subsystem/u_FFT_HDL_Optimized2/u_SDF1_7_1/u_MUL3/prodOfRe 0 1
force -deposit ${::dut_prefix}Subsystem/u_FFT_HDL_Optimized2/u_SDF1_7_1/u_MUL3/prodOfIm 0 1
force -deposit ${::dut_prefix}Subsystem/u_FFT_HDL_Optimized2/u_SDF1_7_1/u_MUL3/prodOfSum 0 1
force -deposit ${::dut_prefix}Subsystem/u_FFT_HDL_Optimized2/u_SDF1_9_1/u_MUL3/Complex3Multiply_din1_re_pipe1 0 1
force -deposit ${::dut_prefix}Subsystem/u_FFT_HDL_Optimized2/u_SDF1_9_1/u_MUL3/Complex3Multiply_din1_im_pipe1 0 1
force -deposit ${::dut_prefix}Subsystem/u_FFT_HDL_Optimized2/u_SDF1_9_1/u_MUL3/Complex3Multiply_din1_sum_pipe1 0 1
force -deposit ${::dut_prefix}Subsystem/u_FFT_HDL_Optimized2/u_SDF1_9_1/u_MUL3/Complex3Multiply_twiddle_re_pipe1 0 1
force -deposit ${::dut_prefix}Subsystem/u_FFT_HDL_Optimized2/u_SDF1_9_1/u_MUL3/Complex3Multiply_twiddle_im_pipe1 0 1
force -deposit ${::dut_prefix}Subsystem/u_FFT_HDL_Optimized2/u_SDF1_9_1/u_MUL3/Complex3Multiply_twiddle_sum_pipe1 0 1
force -deposit ${::dut_prefix}Subsystem/u_FFT_HDL_Optimized2/u_SDF1_9_1/u_MUL3/Complex3Multiply_prodOfRe_pipe1 0 1
force -deposit ${::dut_prefix}Subsystem/u_FFT_HDL_Optimized2/u_SDF1_9_1/u_MUL3/Complex3Multiply_ProdOfIm_pipe1 0 1
force -deposit ${::dut_prefix}Subsystem/u_FFT_HDL_Optimized2/u_SDF1_9_1/u_MUL3/Complex3Multiply_prodOfSum_pipe1 0 1
force -deposit ${::dut_prefix}Subsystem/u_FFT_HDL_Optimized2/u_SDF1_9_1/u_MUL3/prodOfRe 0 1
force -deposit ${::dut_prefix}Subsystem/u_FFT_HDL_Optimized2/u_SDF1_9_1/u_MUL3/prodOfIm 0 1
force -deposit ${::dut_prefix}Subsystem/u_FFT_HDL_Optimized2/u_SDF1_9_1/u_MUL3/prodOfSum 0 1
